[build]
  command = "bun run build"
  publish = "dist"
  SECRETS_SCAN_OMIT_KEYS = "BETTER_AUTH_URL"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
